##
## EPITECH PROJECT, 2018
## Makefile
## File description:
## Makefile
##

SRC	=	main.c	\
		calc.c	\
		my_putint.c	\
		my_put_nbr.c

OBJ	=	$(SRC)

NAME	=	eval_expr

all :	$(OBJ)
	gcc -o $(NAME) $(SRC)

clean:
	rm -f

fclean:
	clean
	rm -f

re:	fclean all
